language: java

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "M40LXdZ+q1ctQ+Z5thByVJcPpATHZIBAmeCFgvCROuOmxPLuoOqYbpJpDsclBywquZ3WhJQ3pk2OCYkptEU9fDDVwLVUmxZFzzNiJuG40hhEQOl8+frH/mz7EXFpnvnIFIrbE/witaCsPaNhKVq7AI5Bt/UkUDhFv+WGuFidCjEI8gyS8KSOGPmXFdCXxFn6zLWp4HJhgmGx2sJmOu/+mcLyR/dF1jzjM1/lb0jmR+qzZB7p4eVD3Q7/Z619pt33jG4H5km6NjIPEWUDwnR/6xlv6HquNYacSzvuqiRYa75JFUqObw1bHZiLiIddl2jU8D+w2tu+REVkDyaVdJICvzwT42GZ4JNEbRBfRcTS3dYk9izcDgYxTLr1wkz4LQC0XhvfLPjepQ+TAfn1e25PumTah40Z3GRBCOi5tRqAWHYWNE+Q+pEroRAcTl3nWQJ2C+EV55Xq2FV1gBKSDFEuuEr2+74Yj5uFh9C7FMpcQM8oo43jJX6adsaqwK6m2kb/aYV2OqvgTHmvhRrkLhEbQCgPNlJpKFbKNmqqBy8QWlmTxnOnF88R+bvSD4z3REoPLRj5KxJmWYpX1YmbIRuZZhRTAAiiQ0fTAoLEWfUcRBZNGMR59eQYy2piIKsR2PeHnO6699qaqFFOuj61rrH6ib1uS1f9b2RIxYMPYl8hA8M="
    - secure: "xpPNformbwaZ3aCVHt/KaCJrK0TOFrNImMIYkGHEMO0VJQcWqpz3E2KEhXb7x54UOmTSBHOhNtD2YJGPuzb9vARkqk44rsgkBFKt/w7ilRRWH8g09vfqALjWupg8LdW8hSUSuMpUovuOxyNKnvn/oTX5XLZNV2N9O+c9JjMc0z/K64ANstA7U+Uu/MXBIP/aaiHTSpimilAd2CuSXEtypwt12IKfSZVVACJoLcuICAvtN/o2r6g9QzRAcVXQcC/i1/pfxgkAhKT1M7jWxZ0BPfjCg5u8wLtTxszdSxVPyMDZB45Ssp4e3woKsIqdzvZC7EiDKcMwUdsxq95WbPu8n079DGy1VvGh0Vx3XnYHGE6oU0r5oyF7YtivJwSEXyoen7r1RMbrw5unSlUhkl7ygk5e6PuPs6GwRTy+51JWH2DyiOvhcSNTKhzclZ4SBc7T3iomMpg9jM4g0PUuT4oK2mwk0G4Ykkby+qaRwO9Pq+G3bQzGEvHGRI2/OkNr+7EaaoscG7t3Vb+awIcOZaKqppn3xku5sS/hiFyLbr8k1BkBV/sreac2xNdMF7JOfMWS6Q8lbuhLzZKAyVjulERx/tE9oQtynDIdFnBYZjeovNM4lDZOa9v9SJc58Kys8jQR+yrc8ZI65SBbRqXXg5vGcKI9GhiowuolfYyCmo80ziQ="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/caches/modules-2/files-2.1
